webtalk_init -webtalk_dir C:/Users/USER/Documents/Lessons/CA-Lab/SPRING-2023/1-start/arm_prj/arm_prj.sim/sim_1/behav/xsim/xsim.dir/design_1_wrapper_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Apr 30 17:59:55 2025" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2405991" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "33414f44-9dd8-43f5-a4af-c95cf24735f1" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "8cf86a9f9ea944a8b258102db2a0b16d" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "19" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "12th Gen Intel(R) Core(TM) i7-12700H" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2688 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "213 ps" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.03_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "8500_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3985488434 -regid "" -xml C:/Users/USER/Documents/Lessons/CA-Lab/SPRING-2023/1-start/arm_prj/arm_prj.sim/sim_1/behav/xsim/xsim.dir/design_1_wrapper_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/USER/Documents/Lessons/CA-Lab/SPRING-2023/1-start/arm_prj/arm_prj.sim/sim_1/behav/xsim/xsim.dir/design_1_wrapper_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/USER/Documents/Lessons/CA-Lab/SPRING-2023/1-start/arm_prj/arm_prj.sim/sim_1/behav/xsim/xsim.dir/design_1_wrapper_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
