@echo off
REM ****************************************************************************
REM Vivado (TM) v2018.3 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Sat May 17 12:05:11 +0330 2025
REM SW Build 2405991 on Thu Dec  6 23:38:27 MST 2018
REM
REM Copyright 1986-2018 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
call xsim tb_design_MEM_wrapper_behav -key {Behavioral:sim_1:Functional:tb_design_MEM_wrapper} -tclbatch tb_design_MEM_wrapper.tcl -protoinst "protoinst_files/design_MEM.protoinst" -protoinst "protoinst_files/design_EX.protoinst" -protoinst "protoinst_files/design_ARM.protoinst" -protoinst "protoinst_files/design_WB.protoinst" -protoinst "protoinst_files/design_ID.protoinst" -protoinst "protoinst_files/design_IF.protoinst" -protoinst "protoinst_files/design_1.protoinst" -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
